title: My Project

navigation:
    - home
    - events
    - people
    - about

singlePage: false

# possible are: vertical, horizontal, table, box
layout: vertical

# more to come
language: php
database_connector: "mysqli"

#
code_style: "snake"


# also possible is 'tables'
# model name should be singular
models:
    user:
        # optional. if not given 's' will be appended to the model name
        plural: "users"
        -
            name:           "name"
            type:           "string"
            visibility:     "private"
        -
            name:           "first_name"
            type:           "string"
            visibility:     "protected"
        -
            name:           "age"
            type:           "integer"
    event:
        -
            name:   "name"
        -
            name:   "begin"
        -
            name:   "end"

database:
    domain:     "localhost"
    user:       "root"
    password:   ""
    name:       "test_db"
