title: My Project

navigation:
    - home
    - events
    - people
    - about

singlePage: false

# possible are: vertical, horizontal, table, box
layout: vertical

# more to come
language: php
database_connector: mysqli

#
code_style: snake


# also possible is 'tables'
# model name should be singular
models:
    user:
        # optional. if not given 's' will be appended to the model name
        -   plural: users
        -
            name:           name
            type:           string
            visibility:     private
        -
            name:           first_name
            type:           string
            visibility:     protected
        -
            name:           age
            type:           integer
    event:
        -
            name:   name
        -
            name:   begin
        -
            name:   end

database:
    domain:     localhost
    user:       root
    password:   ""
    name:       test_db

# more to come: 'advanced' => frontend routing help
routing: simple

# get "master_report/:id", :to => "api#master_report", :format => 'json'
routes:
    # -
    #     type:   get
    #     from:   api/test1
    #     to:     api#test1
    #     # optional. possible is 'json', 'string'. default is 'string'
    #     format: json
    # => api/php?route=get_route1&first_name=ASDF&last_name=BSDF
    get:
        get_route1:
            - first_name
            - last_name
            - format: json
        get_route2:
            - action
    post:
        post_route1:
            - key
        post_route2:
            - data
